const items=[
 {id:1,source:'xiaohongshu',icon:'书',cls:'xhs',title:'别再只会用 ChatGPT：Agent 产品的 5 个设计原则',summary:'从任务拆解、工具调用和反馈机制三个层面，梳理 Agent 产品体验的关键差异。',domain:'AI 产品设计',type:'案例拆解',time:'10 分钟前',c1:'#ff817a',c2:'#d94b58',cover:'AGENT\nDESIGN'},
 {id:2,source:'bilibili',icon:'B',cls:'bili',title:'深入理解 RAG：从检索到生成的完整链路',summary:'用可视化方式解释向量化、召回、重排与生成，适合作为 RAG 入门框架。',domain:'AI 技术基础',type:'视频教程',time:'32 分钟前',c1:'#58c5df',c2:'#357daf',cover:'RAG\n101'},
 {id:3,source:'wechat',icon:'微',cls:'wechat',title:'大模型产品经理的能力地图 2026',summary:'拆解模型理解、场景定义、效果评估和商业化四类核心能力。',domain:'职业成长',type:'行业报告',time:'1 小时前',c1:'#53b98d',c2:'#30755e',cover:'AI PM\nMAP'},
 {id:4,source:'web',icon:'W',cls:'web',title:'How we built memory for AI agents',summary:'长期记忆系统的工程权衡：事件流、语义检索与用户可控性。',domain:'AI 产品设计',type:'技术文章',time:'昨天',c1:'#61708e',c2:'#30384d',cover:'MEMORY\nSYSTEM'},
 {id:5,source:'xiaohongshu',icon:'书',cls:'xhs',title:'零基础搭建个人知识库，我只做了这三步',summary:'轻量知识管理工作流：统一入口、渐进式分类与每周回顾。',domain:'个人成长',type:'方法论',time:'昨天',c1:'#f5a46e',c2:'#df6464',cover:'KNOWLEDGE\nFLOW'},
 {id:6,source:'bilibili',icon:'B',cls:'bili',title:'从用户旅程看 AI 产品的信任设计',summary:'通过真实案例理解预期管理、过程可见性和失败恢复策略。',domain:'用户体验',type:'案例拆解',time:'2 天前',c1:'#8d7dea',c2:'#55458f',cover:'TRUST\nBY DESIGN'}
];
const feedList=document.getElementById('feedList'),libraryGrid=document.getElementById('libraryGrid');
function renderFeed(){feedList.innerHTML=items.slice(0,4).map(x=>`<article class="feed-item" data-id="${x.id}"><div class="source-icon ${x.cls}">${x.icon}</div><div><h3>${x.title}</h3><p><span class="tag">${x.domain}</span><span class="tag">${x.type}</span></p></div><time>${x.time}</time></article>`).join('')}
function renderLibrary(filter='all',query=''){const list=items.filter(x=>(filter==='all'||x.source===filter)&&(`${x.title}${x.summary}${x.domain}${x.type}`.toLowerCase().includes(query.toLowerCase())));libraryGrid.innerHTML=list.map(x=>`<article class="library-card" data-id="${x.id}"><div class="card-cover" style="--c1:${x.c1};--c2:${x.c2}"><span>${x.source==='xiaohongshu'?'小红书':x.source==='bilibili'?'哔哩哔哩':x.source==='wechat'?'公众号':'网页'}</span><strong>${x.cover.replace('\n','<br>')}</strong></div><div class="card-body"><h3>${x.title}</h3><p>${x.summary}</p><div class="card-meta"><span><i class="dot violet"></i> ${x.domain} · ${x.type}</span><time>${x.time}</time></div></div></article>`).join('')||'<p>没有找到匹配的内容</p>'}
renderFeed();renderLibrary();
const days=[['一',52],['二',78],['三',42],['四',88],['五',65],['六',93],['日',36]];document.getElementById('weekBars').innerHTML=days.map(([d,v])=>`<div class="bar-wrap"><div class="bar"><i style="height:${v}%"></i></div><small>${d}</small></div>`).join('');
function go(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`${view}-view`));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
const modal=document.getElementById('modalBackdrop');document.getElementById('quickAdd').onclick=()=>modal.classList.add('show');document.getElementById('modalClose').onclick=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')};
function toast(msg){const t=document.getElementById('toast');t.querySelector('p').textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
document.getElementById('analyzeUrl').onclick=()=>{const state=document.getElementById('analyzeState');if(!document.getElementById('urlInput').value)return toast('请先粘贴一个内容链接');state.classList.add('show');setTimeout(()=>{state.classList.remove('show');modal.classList.remove('show');toast('内容已采集，AI 总结与标签匹配完成')},1800)};
document.querySelectorAll('.filter-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderLibrary(b.dataset.filter,document.getElementById('globalSearch').value)});
document.getElementById('toggleLayout').onclick=e=>{libraryGrid.classList.toggle('list');e.currentTarget.textContent=libraryGrid.classList.contains('list')?'▦ 网格视图':'☷ 列表视图'};
document.getElementById('globalSearch').addEventListener('input',e=>{go('inbox');renderLibrary('all',e.target.value)});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('globalSearch').focus()}if(e.key==='Escape')modal.classList.remove('show')});
document.getElementById('organizeBtn').onclick=e=>{e.currentTarget.textContent='✦ 正在建立语义关联…';setTimeout(()=>{e.currentTarget.innerHTML='✓ 已完成智能整理';toast('12 条内容已归类，新增 18 个知识连接')},1600)};
document.getElementById('buildTopic').onclick=()=>{go('plans');toast('已生成「AI Agent 记忆机制」专题草稿')};
['newPlan','newCard'].forEach(id=>document.getElementById(id).onclick=()=>toast('AI 场景搭建向导已启动'));document.getElementById('startFocus').onclick=()=>{go('plans');toast('已为你定位到上次学习进度')};document.getElementById('enterPlan').onclick=()=>toast('已开始：核心机制 · Agent 如何规划任务');
let scale=1;const graph=document.getElementById('graph');function updateGraph(){graph.style.transform=`scale(${scale})`}document.getElementById('zoomIn').onclick=()=>{scale=Math.min(1.35,scale+.1);updateGraph()};document.getElementById('zoomOut').onclick=()=>{scale=Math.max(.75,scale-.1);updateGraph()};document.getElementById('resetGraph').onclick=()=>{scale=1;updateGraph()};
document.addEventListener('click',e=>{const card=e.target.closest('[data-id]');if(card){const item=items.find(x=>x.id===+card.dataset.id);toast(`已打开：${item.title}`)}});
document.querySelectorAll('.connector .connect-btn').forEach(btn=>btn.onclick=()=>{const platform=btn.closest('.connector').querySelector('h2').textContent;toast(platform==='哔哩哔哩'?'已打开 B站收藏夹映射设置':`已生成${platform}「分享到 LearnFlow」安装指引`)});
document.getElementById('showGuide').onclick=()=>toast('安装指引：在手机分享菜单中启用 LearnFlow');
document.getElementById('syncNow').onclick=e=>{e.currentTarget.textContent='↻ 正在检查…';setTimeout(()=>{e.currentTarget.textContent='✓ 已是最新';toast('三个内容源均已检查，没有遗漏的新内容')},1400)};
