const SUPABASE_URL='https://phzsflusdfgpahbudioz.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_2iwBIs6UFlX8MpaN6DI90w_6_8hxLlY';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let currentUser=null;
const demoItems=[
 {id:1,demo:true,source:'xiaohongshu',icon:'书',cls:'xhs',title:'别再只会用 ChatGPT：Agent 产品的 5 个设计原则',summary:'从任务拆解、工具调用和反馈机制三个层面，梳理 Agent 产品体验的关键差异。',domain:'AI 产品设计',type:'案例拆解',time:'10 分钟前',c1:'#ff817a',c2:'#d94b58',cover:'AGENT\nDESIGN'},
 {id:2,source:'bilibili',icon:'B',cls:'bili',title:'深入理解 RAG：从检索到生成的完整链路',summary:'用可视化方式解释向量化、召回、重排与生成，适合作为 RAG 入门框架。',domain:'AI 技术基础',type:'视频教程',time:'32 分钟前',c1:'#58c5df',c2:'#357daf',cover:'RAG\n101'},
 {id:3,source:'wechat',icon:'微',cls:'wechat',title:'大模型产品经理的能力地图 2026',summary:'拆解模型理解、场景定义、效果评估和商业化四类核心能力。',domain:'职业成长',type:'行业报告',time:'1 小时前',c1:'#53b98d',c2:'#30755e',cover:'AI PM\nMAP'},
 {id:4,source:'web',icon:'W',cls:'web',title:'How we built memory for AI agents',summary:'长期记忆系统的工程权衡：事件流、语义检索与用户可控性。',domain:'AI 产品设计',type:'技术文章',time:'昨天',c1:'#61708e',c2:'#30384d',cover:'MEMORY\nSYSTEM'},
 {id:5,source:'xiaohongshu',icon:'书',cls:'xhs',title:'零基础搭建个人知识库，我只做了这三步',summary:'轻量知识管理工作流：统一入口、渐进式分类与每周回顾。',domain:'个人成长',type:'方法论',time:'昨天',c1:'#f5a46e',c2:'#df6464',cover:'KNOWLEDGE\nFLOW'},
 {id:6,source:'bilibili',icon:'B',cls:'bili',title:'从用户旅程看 AI 产品的信任设计',summary:'通过真实案例理解预期管理、过程可见性和失败恢复策略。',domain:'用户体验',type:'案例拆解',time:'2 天前',c1:'#8d7dea',c2:'#55458f',cover:'TRUST\nBY DESIGN'}
].map(item=>({...item,demo:true}));
let items=[...demoItems];
const feedList=document.getElementById('feedList'),libraryGrid=document.getElementById('libraryGrid');
function renderFeed(){feedList.innerHTML=items.slice(0,4).map(x=>`<article class="feed-item" data-id="${x.id}"><div class="source-icon ${x.cls}">${x.icon}</div><div><h3>${x.title}</h3><p><span class="tag">${x.domain}</span><span class="tag">${x.demo?'演示数据':x.type}</span></p></div><time>${x.time}</time></article>`).join('')||'<div class="cloud-empty">还没有真实收藏，使用 Chrome 扩展开始同步。</div>'}
function renderLibrary(filter='all',query=''){const list=items.filter(x=>(filter==='all'||x.source===filter)&&(`${x.title}${x.summary}${x.domain}${x.type}`.toLowerCase().includes(query.toLowerCase())));libraryGrid.innerHTML=list.map(x=>`<article class="library-card" data-id="${x.id}"><div class="card-cover" style="--c1:${x.c1};--c2:${x.c2};${x.coverUrl?`background-image:linear-gradient(0deg,#17211b99,#17211b22),url('${x.coverUrl}')`:''}"><span>${x.demo?'演示数据':x.source==='xiaohongshu'?'小红书':x.source==='bilibili'?'哔哩哔哩':x.source==='douyin'?'抖音':'网页'}</span><strong>${x.cover.replace('\n','<br>')}</strong></div><div class="card-body"><h3>${x.title}</h3><p>${x.summary}</p><div class="card-meta"><span><i class="dot violet"></i> ${x.domain} · ${x.type}</span><time>${x.time}</time></div></div></article>`).join('')||'<div class="cloud-empty">没有找到匹配的真实收藏</div>'}
renderFeed();renderLibrary();
const authBackdrop=document.getElementById('authBackdrop'),authBtn=document.getElementById('authBtn'),authMessage=document.getElementById('authMessage');
function updateAuthUI(user){currentUser=user;authBtn.textContent=user?(user.user_metadata?.user_name||user.email?.split('@')[0]||'已登录'):'登录';authBtn.classList.toggle('logged-in',!!user);document.querySelector('.profile strong').textContent=user?(user.user_metadata?.user_name||user.email?.split('@')[0]||'已登录'):'访客';document.querySelector('.profile small').textContent=user?'云端同步已开启':'登录后开启云同步'}
function relativeTime(date){const minutes=Math.max(1,Math.floor((Date.now()-new Date(date).getTime())/60000));if(minutes<60)return `${minutes} 分钟前`;if(minutes<1440)return `${Math.floor(minutes/60)} 小时前`;return `${Math.floor(minutes/1440)} 天前`}
function normalizeCloudItem(row){const visual={xiaohongshu:{icon:'书',cls:'xhs',c1:'#ff817a',c2:'#d94b58',cover:'XHS\nNOTE'},bilibili:{icon:'B',cls:'bili',c1:'#58c5df',c2:'#357daf',cover:'BILI\nVIDEO'},douyin:{icon:'♪',cls:'web',c1:'#393d43',c2:'#15171a',cover:'DOUYIN\nVIDEO'},web:{icon:'W',cls:'web',c1:'#61708e',c2:'#30384d',cover:'WEB\nARTICLE'}}[row.source]||{icon:'W',cls:'web',c1:'#61708e',c2:'#30384d',cover:'NEW\nITEM'};return{...visual,id:row.id,source:row.source,title:row.title||'等待解析的收藏内容',summary:row.summary||'已进入 LearnFlow，等待 AI 提取内容并生成结构化摘要。',domain:row.category||'待 AI 归类',type:row.content_type||(row.processing_status==='completed'?'已完成':'待处理'),time:relativeTime(row.collected_at||row.created_at),coverUrl:row.cover_url,url:row.source_url,real:true}}
async function loadCloudItems(){if(!currentUser){items=[...demoItems];renderFeed();renderLibrary();return}const {data,error}=await db.from('learning_items').select('*').order('collected_at',{ascending:false}).limit(100);if(error){toast(`云端数据加载失败：${error.message}`);return}items=(data||[]).map(normalizeCloudItem);renderFeed();renderLibrary()}
async function initAuth(){const {data}=await db.auth.getSession();updateAuthUI(data.session?.user||null);await loadCloudItems();db.auth.onAuthStateChange((_event,session)=>{updateAuthUI(session?.user||null);setTimeout(loadCloudItems,0)})}
initAuth();
authBtn.onclick=async()=>{if(currentUser){if(confirm('要退出当前账号吗？')){await db.auth.signOut();toast('已安全退出')}}else authBackdrop.classList.add('show')};
document.getElementById('authClose').onclick=()=>authBackdrop.classList.remove('show');
authBackdrop.onclick=e=>{if(e.target===authBackdrop)authBackdrop.classList.remove('show')};
document.getElementById('githubLogin').onclick=async e=>{e.currentTarget.disabled=true;e.currentTarget.textContent='正在前往 GitHub…';const {error}=await db.auth.signInWithOAuth({provider:'github',options:{redirectTo:location.origin+location.pathname}});if(error){e.currentTarget.disabled=false;e.currentTarget.innerHTML='<span>⌘</span> 使用 GitHub 登录';authMessage.className='auth-message error';authMessage.textContent=`GitHub 登录失败：${error.message}`}};
document.getElementById('sendMagicLink').onclick=async e=>{const email=document.getElementById('emailInput').value.trim();if(!email||!email.includes('@')){authMessage.textContent='请输入有效的邮箱地址';authMessage.className='auth-message error';return}e.currentTarget.disabled=true;e.currentTarget.textContent='发送中…';authMessage.textContent='正在连接 Supabase Auth…';authMessage.className='auth-message';try{const timeout=new Promise((_,reject)=>setTimeout(()=>reject(new Error('请求超过 15 秒，请检查网络后重试')),15000));const result=await Promise.race([db.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname}}),timeout]);const error=result?.error;authMessage.className=`auth-message${error?' error':''}`;authMessage.textContent=error?`发送失败：${error.message}`:'登录邮件已发送，请前往邮箱点击确认链接。'}catch(error){authMessage.className='auth-message error';authMessage.textContent=`发送失败：${error.message}`}finally{e.currentTarget.disabled=false;e.currentTarget.textContent='发送登录邮件'}};
const days=[['一',52],['二',78],['三',42],['四',88],['五',65],['六',93],['日',36]];document.getElementById('weekBars').innerHTML=days.map(([d,v])=>`<div class="bar-wrap"><div class="bar"><i style="height:${v}%"></i></div><small>${d}</small></div>`).join('');
function go(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`${view}-view`));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
const modal=document.getElementById('modalBackdrop');document.getElementById('quickAdd').onclick=()=>currentUser?modal.classList.add('show'):authBackdrop.classList.add('show');document.getElementById('modalClose').onclick=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')};
function toast(msg){const t=document.getElementById('toast');t.querySelector('p').textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
document.getElementById('analyzeUrl').onclick=async()=>{const state=document.getElementById('analyzeState'),input=document.getElementById('urlInput'),url=input.value.trim();if(!url)return toast('请先粘贴一个内容链接');if(!currentUser){modal.classList.remove('show');authBackdrop.classList.add('show');return}let source='web';if(/douyin\.com|iesdouyin\.com/i.test(url))source='douyin';else if(/bilibili\.com|b23\.tv/i.test(url))source='bilibili';else if(/xiaohongshu\.com|xhslink\.com/i.test(url))source='xiaohongshu';state.classList.add('show');const {error}=await db.from('learning_items').insert({source,source_url:url,title:'待解析的新收藏',sync_method:'manual',processing_status:'pending'});state.classList.remove('show');if(error){toast(error.code==='23505'?'这条内容已经收藏过了':`保存失败：${error.message}`);return}input.value='';modal.classList.remove('show');toast('内容已保存到云端，等待 AI 处理')};
document.querySelectorAll('.filter-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderLibrary(b.dataset.filter,document.getElementById('globalSearch').value)});
document.getElementById('toggleLayout').onclick=e=>{libraryGrid.classList.toggle('list');e.currentTarget.textContent=libraryGrid.classList.contains('list')?'▦ 网格视图':'☷ 列表视图'};
document.getElementById('globalSearch').addEventListener('input',e=>{go('inbox');renderLibrary('all',e.target.value)});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('globalSearch').focus()}if(e.key==='Escape')modal.classList.remove('show')});
document.getElementById('organizeBtn').onclick=async e=>{if(!currentUser){authBackdrop.classList.add('show');return}const original=e.currentTarget.innerHTML;e.currentTarget.disabled=true;e.currentTarget.textContent='✦ AI 正在总结与归类…';try{const timeout=new Promise((_,reject)=>setTimeout(()=>reject(new Error('AI 处理超过 45 秒，请检查 Edge Function 日志')),45000));const {data,error}=await Promise.race([db.functions.invoke('process-learning-items',{body:{limit:8}}),timeout]);if(error)throw error;await loadCloudItems();const firstFailure=data?.results?.find(result=>!result.ok)?.error;if(firstFailure)toast(`成功 ${data.processed||0} 条，失败 ${data.failed||0} 条：${firstFailure}`);else toast(`AI 整理完成：成功 ${data?.processed||0} 条`)}catch(error){toast(`AI 整理失败：${error.message}`)}finally{e.currentTarget.disabled=false;e.currentTarget.innerHTML=original}};
document.getElementById('buildTopic').onclick=()=>{go('plans');toast('已生成「AI Agent 记忆机制」专题草稿')};
['newPlan','newCard'].forEach(id=>document.getElementById(id).onclick=()=>toast('AI 场景搭建向导已启动'));document.getElementById('startFocus').onclick=()=>{go('plans');toast('已为你定位到上次学习进度')};document.getElementById('enterPlan').onclick=()=>toast('已开始：核心机制 · Agent 如何规划任务');
let scale=1;const graph=document.getElementById('graph');function updateGraph(){graph.style.transform=`scale(${scale})`}document.getElementById('zoomIn').onclick=()=>{scale=Math.min(1.35,scale+.1);updateGraph()};document.getElementById('zoomOut').onclick=()=>{scale=Math.max(.75,scale-.1);updateGraph()};document.getElementById('resetGraph').onclick=()=>{scale=1;updateGraph()};
document.addEventListener('click',e=>{const card=e.target.closest('[data-id]');if(card){const item=items.find(x=>String(x.id)===card.dataset.id);if(item?.real&&item.url)window.open(item.url,'_blank','noopener');else if(item)toast(`已打开：${item.title}`)}});
document.querySelectorAll('.connector .connect-btn').forEach(btn=>btn.onclick=()=>{const platform=btn.closest('.connector').querySelector('h2').textContent;toast(platform==='哔哩哔哩'?'已打开 B站收藏夹映射设置':`已生成${platform}「分享到 LearnFlow」安装指引`)});
document.getElementById('showGuide').onclick=()=>toast('安装指引：在手机分享菜单中启用 LearnFlow');
document.getElementById('syncNow').onclick=e=>{e.currentTarget.textContent='↻ 正在检查…';setTimeout(()=>{e.currentTarget.textContent='✓ 已是最新';toast('三个内容源均已检查，没有遗漏的新内容')},1400)};
function xhsNoteId(url){return url?.match(/\/(?:explore|discovery\/item)\/([^/?#]+)/)?.[1]||null}
window.addEventListener('message',async event=>{if(event.source!==window||event.origin!==location.origin||event.data?.source!=='learnflow-chrome-extension'||event.data.type!=='SYNC_XHS_ITEMS')return;const incoming=event.data.payload?.items||[];if(!currentUser){authBackdrop.classList.add('show');toast('请先登录，登录后重新点击扩展同步');return}if(!incoming.length)return;const {data:existing,error:readError}=await db.from('learning_items').select('id,source_url,external_id').eq('source','xiaohongshu');if(readError){toast(`同步检查失败：${readError.message}`);return}const existingByNoteId=new Map((existing||[]).map(row=>[row.external_id||xhsNoteId(row.source_url),row]).filter(([id])=>id));let repaired=0;const fresh=[];for(const item of incoming){const noteId=item.external_id||xhsNoteId(item.source_url);const matched=noteId?existingByNoteId.get(noteId):null;const captured={source_url:item.source_url,external_id:noteId,title:item.title||'小红书收藏笔记',author:item.author||null,cover_url:item.cover_url||null,raw_content:item.raw_content||null};if(matched){const {error}=await db.from('learning_items').update(captured).eq('id',matched.id);if(!error)repaired++;continue}fresh.push({source:'xiaohongshu',...captured,sync_method:'folder',processing_status:'pending'})}if(fresh.length){const {error}=await db.from('learning_items').insert(fresh);if(error){toast(`同步失败：${error.message}`);return}}await loadCloudItems();window.postMessage({source:'learnflow-web-app',type:'SYNC_RECEIVED'},location.origin);toast(`同步完成：新增 ${fresh.length} 条，更新 ${repaired} 条可见内容`);go('inbox')});
